apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xde1c6hzx-go 
  janus-idp.io/tekton: xde1c6hzx-go
  backstage.io/kubernetes-id: xde1c6hzx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xde1c6hzx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml