apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xde1c6hzx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xde1c6hzx-go 
  name: xde1c6hzx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xde1c6hzx-go 
